# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenProgram_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 341)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(10, 30, 241, 21))
        self.inputName.setObjectName("inputName")
        self.listOfApps = QtWidgets.QListWidget(self.centralwidget)
        self.listOfApps.setGeometry(QtCore.QRect(10, 140, 371, 192))
        self.listOfApps.setObjectName("listOfApps")
        self.appName = QtWidgets.QLabel(self.centralwidget)
        self.appName.setGeometry(QtCore.QRect(10, 10, 241, 21))
        self.appName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.appName.setObjectName("appName")
        self.appPath = QtWidgets.QLabel(self.centralwidget)
        self.appPath.setGeometry(QtCore.QRect(10, 60, 241, 21))
        self.appPath.setObjectName("appPath")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(10, 80, 241, 21))
        self.inputPath.setObjectName("inputPath")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 241, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.openPath = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openPath.setObjectName("openPath")
        self.horizontalLayout.addWidget(self.openPath)
        self.removeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(260, 70, 121, 41))
        self.lcdNumber.setObjectName("lcdNumber")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Programms v0.3"))
        self.appName.setText(_translate("MainWindow", "Имя приложения"))
        self.appPath.setText(_translate("MainWindow", "Путь к приложению"))
        self.addButton.setText(_translate("MainWindow", "Добавить"))
        self.openPath.setText(_translate("MainWindow", "Открыть"))
        self.removeButton.setText(_translate("MainWindow", "Убрать"))
        self.label.setText(_translate("MainWindow", " Счетчик приложений"))
