# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Open_Program_settings_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowSettings(object):
    def setupUi(self, windowSettings):
        windowSettings.setObjectName("windowSettings")
        windowSettings.resize(341, 361)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(windowSettings.sizePolicy().hasHeightForWidth())
        windowSettings.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("C:\\Users\\User\\PycharmProjects\\Open-Program\\icos\\app.ico")
        windowSettings.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(windowSettings)
        self.centralwidget.setObjectName("centralwidget")
        self.inputName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputName.setGeometry(QtCore.QRect(10, 30, 321, 21))
        self.inputName.setObjectName("inputName")
        self.appName = QtWidgets.QLabel(self.centralwidget)
        self.appName.setGeometry(QtCore.QRect(10, 10, 241, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.appName.sizePolicy().hasHeightForWidth())
        self.appName.setSizePolicy(sizePolicy)
        self.appName.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.appName.setObjectName("appName")
        self.appPath = QtWidgets.QLabel(self.centralwidget)
        self.appPath.setGeometry(QtCore.QRect(10, 60, 241, 21))
        self.appPath.setObjectName("appPath")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(10, 80, 281, 21))
        self.inputPath.setObjectName("inputPath")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 321, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.removeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.removeButton.setFont(font)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.returnButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.returnButton.setObjectName("returnButton")
        self.horizontalLayout.addWidget(self.returnButton)
        self.dialogChoise = QtWidgets.QPushButton(self.centralwidget)
        self.dialogChoise.setGeometry(QtCore.QRect(300, 80, 31, 21))
        self.dialogChoise.setObjectName("dialogChoise")
        self.listView = QtWidgets.QListWidget(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(10, 140, 321, 211))
        self.listView.setObjectName("listView")
        windowSettings.setCentralWidget(self.centralwidget)

        self.retranslateUi(windowSettings)
        QtCore.QMetaObject.connectSlotsByName(windowSettings)

    def retranslateUi(self, windowSettings):
        _translate = QtCore.QCoreApplication.translate
        windowSettings.setWindowTitle(_translate("windowSettings", "Open-Program"))
        self.appName.setText(_translate("windowSettings", "Имя приложения"))
        self.appPath.setText(_translate("windowSettings", "Путь к приложению"))
        self.addButton.setText(_translate("windowSettings", "Добавить"))
        self.removeButton.setText(_translate("windowSettings", "Убрать"))
        self.returnButton.setText(_translate("windowSettings", "Вернутся"))
        self.dialogChoise.setText(_translate("windowSettings", "<-"))
