# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OpenProgramms_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(221, 41)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputPath = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPath.setGeometry(QtCore.QRect(10, 10, 151, 21))
        self.inputPath.setObjectName("inputPath")
        self.openPath = QtWidgets.QPushButton(self.centralwidget)
        self.openPath.setGeometry(QtCore.QRect(170, 10, 41, 21))
        self.openPath.setObjectName("openPath")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Open Programms v0.1"))
        self.openPath.setText(_translate("MainWindow", "Open"))
